name: mr-tuto
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - dash
  - dash-leaflet
  - dash-bootstrap-components
  - netcdf4
  - numpy
  - opencv
  - rasterio
  - shapely
  - werkzeug<2.1 # 2.1 spews warnings at dev server start
  - xarray
  - pyyaml  # not to be confused with yaml or pyaml!
  - zarr
  - bottleneck
